config/routes.rb
Rails.application.routes.draw do
  resources :monthly_weathers, :only => [:index, :show]

  get 'periods/measure'
  get 'periods/result'

  #resources :weathers, :except => [:new, :delete, :edit]
  resources :weathers, :only => [:index, :show]

  resources :orbits
  resources :engines
  resources :rovers

  get 'mars_overview/mars_weather', to: 'mars_overview#mars_weather'
get 'mars_overview/insight_mission', to: 'mars_overview#insight_mission'
  get 'mars_overview/display', to: 'mars_overview#display'
root 'mars_overview#index'

get '*a', :to => 'errors#routing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/orbit.rb
class Orbit < ApplicationRecord
validates :name, :form,:height, presence: true
  belongs_to :engine
  enum form: {
    'Elliptical' => 'Elliptical',
    'Parabolla' => 'Parabolla',
    'Circular' => 'Circular'
}
 enum height: {
 	'450' => '450',
 	'1050' => '1050',
 	'2055' => '2055'
 }
end

app/controllers/orbits_controller.rb
class OrbitsController < ApplicationController
  before_action :set_orbit, only: [:show, :edit, :update, :destroy]


  # GET /orbits
  # GET /orbits.json
  def index
    @orbits = Orbit.all
    @count = 0
    @orbits.each do |orbit|
      @count += 1
    
    end

  end
  
  def get_period
    @orbit_radius = (params[:height].to_i + 6370)
    return @orbit_radius
    
  end

  # GET /orbits/1
  # GET /orbits/1.json
  def show
  end

  # GET /orbits/new
  def new
    @orbit = Orbit.new
    @engines = Engine.all
  end

  # GET /orbits/1/edit
  def edit
    @engines = Engine.all
  end

  # POST /orbits
  # POST /orbits.json
  def create
    @orbit = Orbit.new(orbit_params)

    respond_to do |format|
      if @orbit.save
        format.html { redirect_to @orbit, notice: 'Orbit was successfully created.' }
        format.json { render :show, status: :created, location: @orbit }
      else
        format.html { render :new }
        format.json { render json: @orbit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orbits/1
  # PATCH/PUT /orbits/1.json
  def update
    respond_to do |format|
      if @orbit.update(orbit_params)
        format.html { redirect_to @orbit, notice: 'Orbit was successfully updated.' }
        format.json { render :show, status: :ok, location: @orbit }
      else
        format.html { render :edit }
        format.json { render json: @orbit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orbits/1
  # DELETE /orbits/1.json
  def destroy
    @orbit.destroy
    respond_to do |format|
      format.html { redirect_to orbits_url, notice: 'Orbit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orbit
      @orbit = Orbit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orbit_params
      params.require(:orbit).permit(:name, :form, :height, :engine_id)
    end
end

app/helpers/orbits_helper.rb
module OrbitsHelper
end

app/views/orbits/_form.html.erb
<%= form_with(model: orbit, local: true) do |form| %>
  <% if orbit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orbit.errors.count, "error") %> prohibited this orbit from being saved:</h2>

      <ul>
        <% orbit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :form %>
    <%= form.select :form,Orbit.forms.keys, prompt: 'Select an orbit shape' %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.select :height,Orbit.heights.keys, prompt: 'Select an orbit height' %>
  </div>

  <div class="field">
    <%= form.label :engine_id %>
    <%= form.collection_select(:engine_id, @engines, :id, :name ) %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', :class => 'linkButton' %>
  </div>
<% end %>

app/views/orbits/edit.html.erb
<h1>Editing Orbit</h1>

<%= render 'form', orbit: @orbit %>

<%= link_to 'Show', @orbit, class: 'linkButton' %> |
<%= link_to 'Back', orbits_path, class: 'linkButton' %>

app/views/orbits/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Orbits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Form</th>
      <th>Height</th>
      <th>Engine</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<img src = "/assets/apod.jpg" width="850" height="450" align = 'right'>

  <tbody>
    <% @orbits.each do |orbit| %>
      <tr>
        <td><%= orbit.name %></td>
        <td><%= orbit.form %></td>
        <td><%= orbit.height %></td>
        <td><%= orbit.engine.name %></td>

        <td>&nbsp;</td>
        <td><%= link_to 'Show', orbit, class: 'linkButton2' %></td>
        <td>&nbsp;</td>
        <td><%= link_to 'Edit', edit_orbit_path(orbit), class: 'linkButton2' %></td>
        <td>&nbsp;</td>
        <td><%= link_to 'Destroy', orbit, method: :delete, data: { confirm: 'Are you sure?' }, class: 'linkButton2' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= "Currently there are" + " " + @count.to_s + " " + "spaceships in orbit"%>

<p><%= link_to 'New Orbit', new_orbit_path, class: 'linkButton' %> | <%=link_to 'Measure Period', '/periods/measure', class: 'linkButton'%></p>

<a href = '/orbits.json' target = '_blank' align = 'bottom'><div class="linkButton">See Json</div></a>

<a href = 'https://api.nasa.gov/planetary/apod?api_key=6hRPShdLwc3NKUIn9ZzWTYOmbpKfWoXPIGmTdEZL' target = '_blank' ><div class="linkButton">See json for image on right</div></a>

app/views/orbits/new.html.erb
<h1>New Orbit</h1>

<%= render 'form', orbit: @orbit %>

<%= link_to 'Back', orbits_path, class: 'linkButton' %>

app/views/orbits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @orbit.name %>
</p>

<p>
  <strong>Form:</strong>
  <%= @orbit.form %>
</p>

<p>
  <strong>Height:</strong>
  <%= @orbit.height %>
</p>

<p>
  <strong>Engine:</strong>
  <%= @orbit.engine.name %>
</p>

<%= link_to 'Edit', edit_orbit_path(@orbit), class: 'linkButton' %> |
<%= link_to 'Back', orbits_path, class: 'linkButton' %>
<br>
<a href = '<%= @orbit.id %>.json' target = '_blank'><div class="linkButton">See Json</div></a>