config/routes.rb
Rails.application.routes.draw do
  resources :monthly_weathers, :only => [:index, :show]

  get 'periods/measure'
  get 'periods/result'

  #resources :weathers, :except => [:new, :delete, :edit]
  resources :weathers, :only => [:index, :show]

  resources :orbits
  resources :engines
  resources :rovers

  get 'mars_overview/mars_weather', to: 'mars_overview#mars_weather'
get 'mars_overview/insight_mission', to: 'mars_overview#insight_mission'
  get 'mars_overview/display', to: 'mars_overview#display'
root 'mars_overview#index'

get '*a', :to => 'errors#routing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/engine.rb
class Engine < ApplicationRecord
	validates :name, :model, :astronauts, presence: true
	enum model: {
    'Falcon' => 'Falcon',
    'Scout' => 'Scout',
    'MG-010' => 'MG-010',
    'Minotaur' => 'Minotaur'
}
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :set_engine, only: [:show, :edit, :update, :destroy]

  # GET /engines
  # GET /engines.json
  def index
    @engines = Engine.all
  end

  # GET /engines/1
  # GET /engines/1.json
  def show
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines
  # POST /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      if @engine.save
        format.html { redirect_to @engine, notice: 'Engine was successfully created.' }
        format.json { render :show, status: :created, location: @engine }
      else
        format.html { render :new }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1
  # PATCH/PUT /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to @engine, notice: 'Engine was successfully updated.' }
        format.json { render :show, status: :ok, location: @engine }
      else
        format.html { render :edit }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1
  # DELETE /engines/1.json
  def destroy
    @engine.destroy
    respond_to do |format|
      format.html { redirect_to engines_url, notice: 'Engine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engine
      @engine = Engine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engine_params
      params.require(:engine).permit(:name, :model, :astronauts)
    end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_form.html.erb
<%= form_with(model: engine, local: true) do |form| %>
  <% if engine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(engine.errors.count, "error") %> prohibited this engine from being saved:</h2>

      <ul>
        <% engine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.select :model,Engine.models.keys, prompt: 'Select a rocket model' %>
  </div>

  <div class="field">
    <%= form.label :astronauts %>
    <%= form.number_field :astronauts %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', :class => 'linkButton' %>
  </div>
<% end %>

app/views/engines/edit.html.erb
<h1>Editing Rocket</h1>

<%= render 'form', engine: @engine %>

<%= link_to 'Show', @engine, class: 'linkButton' %> |
<%= link_to 'Back', engines_path, class: 'linkButton' %>

app/views/engines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rockets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
      <th>Astronauts</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<iframe src="https://giphy.com/embed/S99cgkURVO62qemEKM" width="380" height="270" align = 'right' frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/nasa-nasareactions-S99cgkURVO62qemEKM"></a></p>
  <tbody>
    <% @engines.each do |engine| %>
      <tr>
        <td><%= engine.name %></td>
        <td><%= engine.model %></td>
        <td><%= engine.astronauts %></td>
        <td>&nbsp;</td>
        <td><%= link_to 'Show', engine, class: 'linkButton2' %></td>
        <td>&nbsp;</td>
        <td><%= link_to 'Edit', edit_engine_path(engine), class: 'linkButton2' %></td>
        <td>&nbsp;</td>
        <td><%= link_to 'Destroy', engine, method: :delete, data: { confirm: 'Are you sure?' }, class: 'linkButton2' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rocket', new_engine_path, class: 'linkButton' %>
<br>
<a href = '/engines.json' target = '_blank'><div class="linkButton">See Json</div></a>

app/views/engines/new.html.erb
<h1>New Rocket</h1>

<%= render 'form', engine: @engine %>

<div class="linkButton"><%= link_to 'Back', engines_path %></div>

app/views/engines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @engine.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @engine.model %>
</p>

<p>
  <strong>Astronauts:</strong>
  <%= @engine.astronauts %>
</p>

<div class="linkButton"><%= link_to 'Edit', edit_engine_path(@engine) %></div> |
<div class="linkButton"><%= link_to 'Back', engines_path %></div>
<br>
<a href = '<%= @engine.id %>.json' target = '_blank'><div class="linkButton">See Json</div></a>