config/routes.rb
Rails.application.routes.draw do
  resources :monthly_weathers, :only => [:index, :show]

  get 'periods/measure'
  get 'periods/result'

  #resources :weathers, :except => [:new, :delete, :edit]
  resources :weathers, :only => [:index, :show]

  resources :orbits
  resources :engines
  resources :rovers

  get 'mars_overview/mars_weather', to: 'mars_overview#mars_weather'
get 'mars_overview/insight_mission', to: 'mars_overview#insight_mission'
  get 'mars_overview/display', to: 'mars_overview#display'
root 'mars_overview#index'

get '*a', :to => 'errors#routing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rover.rb
class Rover < ApplicationRecord
	validates :name, :model, :purpose, presence: true
	enum model: {
    'Soujouner Pathfinder' => 'Soujouner Pathfinder',
    'Spirit & Opportunity' => 'Spirit & Opportunity',
    'Mars 2020' => 'Mars 2020',
    'Curiosity' => 'Curiosity',
  
  }
  	enum purpose: {
  		'life suitability' =>  	'life suitability',
  		'analyse ecosystem' => 'analyse ecosystem',
  		'analyse atmosphere' => 'analyse atmosphere',
  		'analyse biocells' => 'analyse biocells',
  		'hang around' => 'hang around'
  		

  	}
end

app/controllers/rovers_controller.rb
class RoversController < ApplicationController
  before_action :set_rover, only: [:show, :edit, :update, :destroy]

  # GET /rovers
  # GET /rovers.json
  def index
    @rovers = Rover.all
  end

  # GET /rovers/1
  # GET /rovers/1.json
  def show
  end

  # GET /rovers/new
  def new
    @rover = Rover.new
  end

  # GET /rovers/1/edit
  def edit
  end

  # POST /rovers
  # POST /rovers.json
  def create
    @rover = Rover.new(rover_params)

    respond_to do |format|
      if @rover.save
        format.html { redirect_to @rover, notice: 'Rover was successfully created.' }
        format.json { render :show, status: :created, location: @rover }
      else
        format.html { render :new }
        format.json { render json: @rover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rovers/1
  # PATCH/PUT /rovers/1.json
  def update
    respond_to do |format|
      if @rover.update(rover_params)
        format.html { redirect_to @rover, notice: 'Rover was successfully updated.' }
        format.json { render :show, status: :ok, location: @rover }
      else
        format.html { render :edit }
        format.json { render json: @rover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rovers/1
  # DELETE /rovers/1.json
  def destroy
    @rover.destroy
    respond_to do |format|
      format.html { redirect_to rovers_url, notice: 'Rover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rover
      @rover = Rover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rover_params
      params.require(:rover).permit(:name, :model, :purpose)
    end
end

app/helpers/rovers_helper.rb
module RoversHelper
end

app/views/rovers/_form.html.erb
<%= form_with(model: rover, local: true) do |form| %>
  <% if rover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rover.errors.count, "error") %> prohibited this rover from being saved:</h2>

      <ul>
        <% rover.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p><img src = "/assets/walle.jpg" width="650" height="450" align = "right">
</p>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.select :model,Rover.models.keys, prompt: 'Select a rover model' %>
  </div>

  <div class="field">
    <%= form.label :purpose %>
    <%= form.select :purpose,Rover.purposes.keys, prompt: 'Select a rover purpose' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', :class => 'linkButton' %>
  </div>
<% end %>

app/views/rovers/edit.html.erb
<h1>Editing Rover</h1>

<%= render 'form', rover: @rover %>

<%= link_to 'Show', @rover, :class => 'linkButton' %> |
<%= link_to 'Back', rovers_path, :class => 'linkButton' %>

app/views/rovers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rovers</h1>

<table>
  <thead>
    <tr>
      <th>Name &nbsp;</th>
      <th>Model &nbsp;</th>
      <th> &nbsp;Purpose</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <p><img src = "/assets/walle.jpg" width="650" height="450" align = "right">
</p>

  <tbody>
    <% @rovers.each do |rover| %>
      <tr>
      
        <td><%= rover.name %></td>
        <td><%= rover.model  %></td> 
        <td><%= rover.purpose %></td>
        <td>&nbsp;</td>
        <td><%= link_to 'Show', rover, :class => 'linkButton2' %></td>
        <td>&nbsp;</td>
        <td><%= link_to 'Edit', edit_rover_path(rover), :class => 'linkButton2' %></td>
        <td>&nbsp;</td>
        <td><%= link_to 'Destroy', rover, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'linkButton2' %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rover', new_rover_path, :class => 'linkButton' %>
<br>
<a href = '/rovers.json' target = '_blank' align = 'bottom'><div class="linkButton">See Json</div></a>

app/views/rovers/new.html.erb
<h1>New Rover</h1>

<%= render 'form', rover: @rover %>

<%= link_to 'Back', rovers_path, :class => 'linkButton' %>

app/views/rovers/show.html.erb
<p id="notice"><%= notice %></p>
<p><img src = "/assets/walle.jpg" width="650" height="450" align = "right">
</p>
<p>
  <strong>Name:</strong>
  <%= @rover.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @rover.model %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @rover.purpose %>
</p>

<%= link_to 'Edit', edit_rover_path(@rover), :class => 'linkButton' %> |
<%= link_to 'Back', rovers_path, :class => 'linkButton' %>
<br>
<a href = '<%= @rover.id %>.json' target = '_blank'><div class="linkButton">See Json</div></a>