config/routes.rb
Rails.application.routes.draw do
  resources :monthly_weathers, :only => [:index, :show]

  get 'periods/measure'
  get 'periods/result'

  #resources :weathers, :except => [:new, :delete, :edit]
  resources :weathers, :only => [:index, :show]

  resources :orbits
  resources :engines
  resources :rovers

  get 'mars_overview/mars_weather', to: 'mars_overview#mars_weather'
get 'mars_overview/insight_mission', to: 'mars_overview#insight_mission'
  get 'mars_overview/display', to: 'mars_overview#display'
root 'mars_overview#index'

get '*a', :to => 'errors#routing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_menu.html.erb
<html>

 
<div class = "nav-container" role = "navigation">
<nav class="nav nav-pills">
 
  <li><%= link_to "Home" ,"/"%></li>
  <li><%= link_to "Mars Weather", "/mars_overview/mars_weather"%></li>
  <li><%= link_to "Insight Mission", "/mars_overview/insight_mission" %></li>
  <li><%= link_to "Create a Rover", rovers_path %></li>
  <li><%= link_to "Deploy a Rocket", engines_path %></li>
  <li><%= link_to "Launch in Orbit", orbits_path %></li>
  <li><%= link_to "Historical weather Data", weathers_path %></li>
  <li><%= link_to "2018 Average Monthly Temperatures", monthly_weathers_path %></li>
</nav>
</div>

<body>


<style>
body {
	background-image: url("/assets/background.jpg ");
    background-repeat:no-repeat;
    background-size:cover;
  background-attachment: fixed;
} 

</style>
 

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.highcharts.com/highcharts.js">git</script>
  </head>

  <body>
    <%= render :partial=>'layouts/menu' %>
    <%= yield %>
  </body>
</html>